export const SET_CUSTOMER = 'SET_CUSTOMER'

export const SET_SHADE = 'SET_SHADE'

export const SET_SLIDER = 'SET_SLIDER'

export const SET_PLAY = 'SET_PLAY'

export const SET_PLAY_LIST = 'SET_PLAY_LIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_PLAYING = 'SET_PLAYING'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_PLAY_LOADING = 'SET_PLAY_LOADING'

export const SET_SHOW_PLAY_LIST = 'SET_SHOW_PLAY_LIST'

export const SET_SHOW_PERSON_FM = 'SET_SHOW_PERSON_FM'

export const SET_PERSON_PLAYING = 'SET_PERSON_PLAYING'

export const SET_ARTISTS_DETAIL = 'SET_ARTISTS_DETAIL'

export const SET_ARTIST_PAGE_INDEX = 'SET_ARTIST_PAGE_INDEX'

export const SET_STATIONS_DETAIL = 'SET_STATIONS_DETAIL'

export const SET_SEARCH_PAGE_INDEX = 'SET_SEARCH_PAGE_INDEX'

export const SET_CURRENT_SEARCH = 'SET_CURRENT_SEARCH'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'
